// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiRepositorioGenerico.Model;

namespace apiRepositorioGenerico.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiRepositorioGenerico.Model.Repositorio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TipoRepositorioid");

                    b.Property<string>("descripcion");

                    b.Property<DateTime>("fechaIng");

                    b.Property<int>("tipoID");

                    b.Property<int>("usuario");

                    b.HasKey("id");

                    b.HasIndex("TipoRepositorioid");

                    b.ToTable("Repositorio");
                });

            modelBuilder.Entity("apiRepositorioGenerico.Model.TelefonoRepositorio", b =>
                {
                    b.Property<int>("idRepositorio");

                    b.Property<string>("telefono")
                        .HasMaxLength(20);

                    b.HasKey("idRepositorio");

                    b.ToTable("TelefonoRepositorio");
                });

            modelBuilder.Entity("apiRepositorioGenerico.Model.TipoRepositorio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion");

                    b.Property<DateTime>("fechaIng");

                    b.HasKey("id");

                    b.ToTable("TipoRepositorio");
                });

            modelBuilder.Entity("apiRepositorioGenerico.Model.Repositorio", b =>
                {
                    b.HasOne("apiRepositorioGenerico.Model.TipoRepositorio")
                        .WithMany("Repositorios")
                        .HasForeignKey("TipoRepositorioid");
                });

            modelBuilder.Entity("apiRepositorioGenerico.Model.TelefonoRepositorio", b =>
                {
                    b.HasOne("apiRepositorioGenerico.Model.Repositorio", "Repositorio")
                        .WithMany()
                        .HasForeignKey("idRepositorio")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
